### ISSUE TITLE
Negative numbers on yend that make the library crash

### ISSUE THREAD

**Issue by javi11** [mnightingale/rapidyenc#3]
Hey, there is a special case that is causing me an error using the library:

I see that when src Is equals to `yend size=750000 part=8525 pcrc32=ACBE5763\r\n.\r\n`
The values returned by decodedDecremental are 
`
nd: 0
ns: 1
end: 1
`

With these values, this part of the code: https://github.com/mnightingale/rapidyenc/blob/8792729266a137af0d5b5896b703e2e5607c4578/decoder.go#L191,
decrements the ns - 2 making it negative number and therefore the library crash with:

`
panic: runtime error: slice bounds out of range [-1:] goroutine 474 [running]: github.com/mnightingale/rapidyenc.(*Decoder).Transform(0xc0002465a0, {0xc002af3000, 0x1000, 0x1000}, {0xc000172000, 0x2c, 0x1000}, 0x0) /go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20231127201145-8792729266a1/decoder.go:206 +0x915 github.com/mnightingale/rapidyenc.(*Decoder).Read(0xc0002465a0, {0xc0045651b0, 0x20e50, 0xc0002465a0?}) /go/pkg/mod/github.com/mnightingale/rapidyenc@v0.0.0-20231127201145-8792729266a1/decoder.go:142 
`

I solved by adding a check after the switch case in which
`
if nSrc < 0 {
	return nDst, 1, io.EOF
}
`

But not sure if is correct or not because I don't fully understand the code. Do you think is a good solution? I can do a pr for it

**Comment by mnightingale** [comment]
Thanks for the report, if possible can you try out #4 and see if it resolved your problem?

It might be a little trickly to reproduce consistently in normal use, I think what could happen is one read ends with `\r\n=` and the next starts `yenc` hence is tried to backtrack too much since the `=` is no longer in the buffer.

**Comment by javi11** [comment]
Yes is working fine now. It is a rare case but it happened to me sometimes in my tests :)
