### ISSUE TITLE
Memory leak on decoder

### ISSUE THREAD

**Issue by javi11** [mnightingale/rapidyenc#5]
https://github.com/mnightingale/rapidyenc/blob/354d8545b0ff84e3b64c97cae17d8624b4e5a5ea/decoder.go#L37C7-L37C18

![Captura de pantalla 2024-01-24 a las 8 09 02](https://github.com/mnightingale/rapidyenc/assets/3855051/a94afc9b-2ca2-40ef-8a18-a4c9dfa4f2f9)

I think there may be a memory leak on the decoder. Under high pressure, decoders are being created, but they are never released, so the decoders pool grows without control.

Maybe a limit is needed or a way to clean up

**Comment by mnightingale** [comment]
Could you share the full pprof image or report?

I've tried a couple of tings, first testing with a worker per connection (100) looping over a channel of requests (100000) of 1MB raw data each read out with `io.Copy(io.Discard, dec)` over 300 new `rapidyenc.Decoder` instances created but memory usage is flat at ~30MB.

Instead reading to a bytes.Buffer, 18500 decoder instances were created, memory usage hits ~180 MB, settles at 60MB before eventually falling to ~35 MB while idle.

I wonder if you could see how many new Decoders you are creating and verify all are being released?

**Comment by javi11** [comment]
Here you have the profile : [profile (5).zip](https://github.com/mnightingale/rapidyenc/files/14048892/profile.5.zip)

I will try to check if I can provide the number of decoders, but I am not sure if the leak is at that point, I just thought it could be there since, decoders are being created and put it back into the pool and there is no limit for that. 

I put the decoder acquire and release in a place where it can be very aggressive there can be a lot of routines at the same time executing that part, meaning that there is the need to create a lot of decoders simultaneously. 
Now I'm trying a new approach where I only acquire a new decoder "peer session", let's see how it behaves.

**Comment by javi11** [comment]
I will close it since I can not reproduce it any more :)
