### ISSUE TITLE
NgPost uploads give CRC32 mismatch

### ISSUE THREAD

**Issue by javi11** [mnightingale/rapidyenc#7]
Hey, not sure if is something related to rapidyenc but I always got CRC32 mismatch for articles uploaded by ngpost

 "[rapidyenc] expected decoded data to have CRC32 hash 0x00623e46 but got 0x0623e468: crc32 mismatch"

For instance, this is the article ID 544257ad6ba44c02aa66d94a80b68fed@ngPost

Any idea why?
I will try to debug a bit to give you more context

**Comment by mnightingale** [comment]
Article has `=yend size=716800 pcrc32=623e468` so only 7 hex characters, yEnc spec says it should be 8 with leading zeros.

But there are a few posters which incorrectly format crc values, currently it handles even numbers but I'll make it also handle these odd lengths.

Thanks for reporting!

**Comment by javi11** [comment]
Thanks for your amazing work

**Comment by mnightingale** [comment]
Above PR should have resolved the problem.

One day I'll feel its read for tagging a v1 release and add a readme 😄

**Comment by javi11** [comment]
wow that was fast, it works all as expected. Thanks ❤️
